src/app/editor.js
tests/unit/editor.js

Several enhancements to the submit button state handling

---

src/extension/manifest.json

Partially fixes #173 for the GitHub.com case. Amazon S3 is still pending.

Removed the manifest permissions request for GitHub.com

---

src/app/editor/editor.js
src/app/features/codeditor.js
src/app/features/codelinecommenteditor.js
src/app/features/commenteditor.js
src/app/features/milestoneeditor.js
src/app/features/newcodeditor.js
src/app/features/newcommenteditor.js
src/app/features/newinlinecommenteditor.js
src/app/features/newissueeditor.js
src/app/features/newpullrequesteditor.js
src/app/features/releaseeditor.js
src/app/features/revieweditor.js
src/app/features/savedreplyeditor.js
src/app/features/wikieditor.js

Fixed the editor class name in the production build

---

src/github-writer.css

Updated the border-radius value of `.ck-content` so the border is visible around the content correctly. Closes #311.

Updated content border styling

---

src/extension/manifest.json

Updated manifest version as the current one will be deprecated in 2023 based on [google migration guide](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/). Closes: #320.

Updated manifest to v3

---

src/github-writer.css

Long text should no longer overlap the 'commit changes area button'. Closes #266.

Fixed long text overlaping commit button

---

src/app/editor/ckeditorgithubeditor.js

All pasted/uploaded images should now be a block image by default. Resolves #343.

Removed inline images support

---

src/github-writer.css

Toolbar buttons tooltips should now be visible when editing comment. Closes #347.
Additional information:  
This solution is reverting a part of the changes introduced while working on the #326.

Toolbar tooltips visibility improved.

---

src/app/router.js
tests/unit/router.js

The GHW's router listened to pjax events to detect when it should destroy the old editors and initialize new ones. However, it seems that GH no longer uses the pjax and it uses [Turbo](https://turbo.hotwired.dev/) instead. I've replaced the pjax events with their [Turbo equivalents](https://turbo.hotwired.dev/reference/events):
*   `pjax:start` → `turbo:before-visit`,
*   `pjax:end` → `turbo:render`.
Thanks to that, the navigation between pages is correctly detected and handled and GHW is once again loading correctly.
Closes #337.

Fix for partial loading or not loading at all of the GitHub Writer

---

src/extension/popup/popup.html

- Add correct link to the site in `popup.html`

fix(popup): link typo to website

---

src/app/plugins/wordfinder.js

Fixing warning messages for deprecated string parameter instead of batch object. Closes #331.

Add proper batch object to watchChanges function

---

src/app/plugins/modeswitcher.js
tests/unit/plugins/modeswitcher.js

The tooltip for switching to/from markdown mode button, will now have the expected text. Closes #378.

Wrong tooltip for markdown switch button

---

tests/unit/dependencies/ckeditor5-markdown-gfm.js
tests/unit/plugins/autoformat.js

The change was actually very simple. Closes #392.

Fixed CKE5 plugin paths in unit tests

---

src/app/plugins/headingdropdown.js
src/app/plugins/smartcode.js

Focus and selection will now remain on the text when the Heading or Code buttons are pressed. Closes #380.

Updated focus behavior for heading and code.

---

src/app/theme/panel.css

After the recent editor update to v 35.2.1 it was necessary to update css for tooltips when using `sync-with-system` theme. Closing #390.

Updated css for sync-with-system tooltips.

---

src/app/router.js
tests/unit/router.js

To test the PR, build the dev version, open dev tools and navigate throughout GH. As long as there is no hard reload (console will clear then) you should see that every Writer instance that is created is also destroyed after leaving a page (follow the notes in console).
Closes #416.

Fix memory leaks

---

tests/unit/plugins/savedreplies.js

Updates test for focus in saved replies so it does not fail. Closes #421.
Additional information:
This fix was needed because we recently removed duplicated `focus()` call in https://github.com/ckeditor/github-writer/pull/395.

Update test for focus in saved replies.

---

src/app/router.js

I decided to edit the regexp to avoid the attempt to create the editor on the `issues/new/choose` pages as it seemed the easiest thing to do, but there are other possibilities, e.g. perhaps the queries should be improved instead - I'm open for proposals.
Closes #426.

Don't try to create the editor at 'issues/new/choose' page

---

src/app/plugins/githubuploadadapter.js
src/app/theme/content.css

To get correct url we need to do one more fetch (like GitHub does).
Closes #444.

Fix for uploading images.

---

src/app/editor/editor.js

Less specificity of `CSS` selectors searching `DOM` elements during editor creating (panels: `markdown` and `preview`).
Closes: https://github.com/ckeditor/github-writer/issues/453

Edit issue or comment should not throw any errors.

---

src/app/editor/editor.js
src/app/features/wikieditor.js
src/github-writer.css
tests/_util/githubpage.js
tests/_util/html/root.html
tests/compat/issue-new.js

Extension should now work for Issues and Wiki pages in Chrome and Firefox.
Closes #470.

Extension should work for Issues and Wiki pages
