ckeditor/github-writer

src/app/editor.js, src/app/editors/rteeditor.js, src/app/editors/wikirteeditor.js, src/github-writer.css, tests/unit/editor.js, tests/unit/editors/rteeditor.js, tests/unit/editors/wikirteeditor.js
=> Introduced auto-resizing

src/app/plugins/livemodeldata.js, tests/unit/plugins/livemodeldata.js, tests/unit/plugins/messenger.js
=> Switched editor.model.data to JSON

src/app/editors/rteeditor.js, tests/unit/editors/rteeditor.js
=> Avoiding nbsp around emojis in the data output

src/app/editor.js, tests/unit/editor.js
=> Update session data when moving to RTE as well

src/app/editor.js, tests/unit/editor.js
=> Fixed the form locking status when canceling mode switch

src/app/editor/createeditormixin.js, src/app/modules/util.js, tests/unit/editor/createeditormixin.js, tests/unit/modules/util.js
=> Pjax clicks inside the editable are now blocked

src/app/editor/ckeditorgithubeditor.js, src/app/plugins/general.js, tests/unit/plugins/general.js
=> Table insertion will now have a header row by default

src/app/editor/ckeditorconfig.js, src/app/editor/modemixin.js, src/app/editor/submitstatusmixin.js, src/app/features/codeditor.js, src/app/features/newcodeditor.js, src/app/plugins/modeswitcher.js, src/app/router.js, src/app/theme/content.css, src/extension/manifest.json, src/github-writer.css, tests/_pom/pages/fileeditpage.js, tests/_pom/pages/pullrequestpage.js, tests/_util/githubpage.js, tests/_util/html/root.html, tests/unit/editor/ckeditorconfig.js, tests/unit/editor/modemixin.js, tests/unit/editor/submitstatusmixin.js, tests/unit/features/codeditor.js, tests/unit/features/newcodeditor.js, tests/unit/plugins/modeswitcher.js
It includes support for editing and creation of markdown files. It includes support for image upload.
Closes #171.
=> Introduced GitHub Writer in the file editing page

dev/webpack.config.js, src/app/modules/util.js, src/extension/manifest.json
=> Remove all permission requests from the Chrome manifest.

src/app/features/newcommenteditor.js, src/app/features/newinlinecommenteditor.js, src/github-writer.css
=> Fixed the auto-grow in new comment editors

src/app/editor/ckeditorgithubeditor.js
=> Disabled the "Heading TAB Key" plugin

src/app/plugins/autoformat.js, tests/unit/plugins/autoformat.js
=> Allowed for inline auto-formatting inside parenthesis and quotes

src/app/theme/autolink.css, src/app/theme/codeblock.css, src/app/theme/content.css, src/app/theme/filteredlist.css, src/app/theme/githubwriter.css, src/app/theme/mentions.css, src/app/theme/panel.css, src/app/theme/toolbar.css, src/github-writer.css
Fixes #238.
This is a followup to #239.
=> Compatibility with the Dark Theme

src/app/plugins/autoformat.js, tests/unit/plugins/autoformat.js
=> Added auto-formatting for todo lists

src/app/theme/content.css, src/app/theme/githubwriter.css, src/app/theme/mermaid.css
Hid the placeholder so it's no longer visibile over the mermaid widget.  
Resolved issues with borders overlapping when inserting other widgets after mermaid.  
Updated font color for mermaid editing part.
=> Mermaid widget UI fixes part 2

src/app/editor/ckeditorconfig.js, src/app/editor/ckeditorgithubeditor.js
It is now possible to set an alternative text for the image by using the image toolbar. Closes: #10.
=> Introduced image text alternative

dev/updateemojis.js, src/app/data/emojis.json
Bumped the emoji compatibility. Closes https://github.com/ckeditor/github-writer/issues/321.
=> Emoji compatibility updated.

src/app/editor/ckeditorconfig.js
Merge/split of table cells should now be possible. Resolves #330.
=> Tables merge/split functionality added

src/app/features/revieweditor.js, tests/_pom/pages/pullrequestpage.js, tests/_util/githubpage.js
GH Writer should now correctly load in the review comment textarea. Resolves: https://github.com/ckeditor/github-writer/issues/345.
=> Review comment editor should now work correctly.

src/app/router.js
Updated page name for replies in router.js so it loads correctly. Closes https://github.com/ckeditor/github-writer/issues/396.
=> Updated page name for replies in router.

tests/unit/plugins/enter.js
Updates tests for Enter so they don't fail anymore. Closes #422.
=> Update tests for Enter.

package.json, src/app/editor/setupmixin.js
Restore the ability to submit review form.
I had to change `@ckeditor/ckeditor5-mermaid` dependency to get [latest changes](https://github.com/ckeditor/ckeditor5-mermaid/commit/d6293b76ef9bcd0dac1eee4bc2560c5fbbcc88b2) to avoid build errors.
Closes #443
=> Submit review with Writer.
